const router         = require('express').Router();
const requireAuth    = require('../common/authMiddleware');
const resumeController = require('./resume.controller');

/**
 * POST /api/resume/generate
 * Generate a resume using the provided form data.
 * AI fills in any missing summary or experience bullets.
 */
router.post('/generate', requireAuth, resumeController.generateResume);

/**
 * GET /api/resume/history
 * Return the last 20 resumes generated by the current user.
 */
router.get('/history', requireAuth, resumeController.getHistory);

module.exports = router;